### ISSUE TITLE
User profile - Viewed products - Arrow appears on product card next to image

### ISSUE THREAD

**Issue by hardstonepaul** [Boton-Promo/shopify_theme#21]
@Slaternight 

![image](https://github.com/user-attachments/assets/d5c7232c-a0e8-4d93-ade1-b2c3836d7200)

What is this arrow when user make a hover on the product.

**Comment by Slaternight** [comment]
I don`t see it

**Comment by hardstonepaul** [comment]
https://esferos.com/account?a=cd_recently-viewed

![Image](https://github.com/user-attachments/assets/bb3fa753-8b82-4b62-b038-c29de623b1a3)

When pointer is over the name of product.

**Comment by Slaternight** [comment]
Done?

<img width="902" height="398" alt="Image" src="https://github.com/user-attachments/assets/692aaee4-aa58-49a9-965f-cfe6bdb1fb2e" />

**Comment by hardstonepaul** [comment]
try this code in the CSS:
```css
.customerdb-parent .cd_tooltiptext {
  visibility: hidden;
  width: 200px;
  background-color: black;
  color: #fff;
  text-align: center;
  border-radius: 6px;
  padding: 2px;
  position: absolute;
  z-index: 1;
  bottom: 150%;
  left: 0;
  bottom: 32px;
}
```

**Comment by hardstonepaul** [comment]
Now we have to change the size of the `img`
```css
.customerdb-parent .cd_products_card_img, .customerdb-parent .cd_top_ordered_products_card__img, .customerdb-parent .cd_recently_viewed_products_card__img {
  display: flex;
  width: 100%;
  align-items: center;
  min-height: 100px;
  margin-left: auto;
  margin-right: auto;
  margin-bottom: 10px;
}
```
